### ISSUE TITLE
Review Wiki

### ISSUE THREAD

**Issue by hannhow** [uoForms/BI_Dashboarding#2]

**Comment by hannhow** [comment]
Please review the wiki and provide your comments.

**Comment by aasam028** [comment]
- The first thing we are missing is a tutorial defining the interface to users. How to login and how to Navigate. 
- Also with the tutorials, Kindly arrange it in this way.. Slice, Group and Group by, other functions...  Before building Klip.
- Dashboard should also be defined under Klipfolio 101.

- A sample video can also be added from You tube..

**Comment by Sunerbones** [comment]
- Home page should provide a brief introduction about what this wiki entails and what outcomes are expected after finishing reading and learning the wiki;

- About Klipfolio could be a sub-section of Klipfolio 101;

- Could add Klipfolio advanced sections for users who want to learn more.

**Comment by Sunerbones** [comment]
**_BI Introduction Page:_** "In all cases, BI is most effective when it combines data derived from the market in which a company operates (external data) with data from company sources internal to the business such as financial and operations data (internal data). " = Reword this sentence...Right now it's too complicated for users to follow.

**_Architecture_** - Provide a high-level architecture graph illustrating Klipfolio framework; Elaborate more on integrating multiple data sources details. 

**_Klipfolio 101_** - After introducing Klip and data sources, add **"Dashboard"** part.

**Comment by Sunerbones** [comment]
After walking through the whole wiki and finished the Klipfolio course. Here are some suggestions.
1. If project is not needed, please delete the project section.
2. Assignment Instruction Issues:
   -  Assignment 1: Please indicate clearly for sorting, percentage and number of slices requirements.
   -  Assignment 2: Please indicate the use of the user input control towards assignment 3, which is helping readers understand when prompting the next assignments.
   -  Assignment 3: 1) One typo found, created a "bar" chart, instead of "pie" chart. 
![image](https://cloud.githubusercontent.com/assets/11786914/13802039/2ac0d040-eb0e-11e5-9606-2ae898254b7f.png)
                              2) Function errors found and fixed.
                              3) Process walkthrough: For beginners, it's easier for learners to understand how functions work if the steps are from X-Axis to Series. (X-Axis structure is required before prompting to populate series.)
